version: "3.3"

networks:
  proxy:
    external: true

volumes:
  database:

services:
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    environment:
      # TODO: figure out how this can be moved to secrets instead
      MYSQL_ROOT_PASSWORD: yourrootpassword
      MYSQL_DATABASE: identity-provider
      MYSQL_USER: identity-provider
      MYSQL_PASSWORD: youruserpassword
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - proxy
