version: "3.3"

networks:
  proxy:
    external: true

volumes:
  database:

services:
  mariadb:
    image: jsurf/rpi-mariadb
    volumes:
      - database:/var/lib/mysql
    environment:
      # TODO: figure out how this can be moved to secrets instead
      MYSQL_ROOT_PASSWORD: yourrootpassword
      MYSQL_DATABASE: momin
      MYSQL_USER: momin
      MYSQL_PASSWORD: yourrootpassword
    deploy:
      placement:
        constraints:
          - node.labels.persistence == mysql
      labels:
        - traefik.docker.network=proxy
        - traefik.port=3306
        - traefik.enable=true
    networks:
      - proxy
