version: "3.3"

networks:
  proxy:
    external:
      name: proxy

configs:
  traefik-toml-v2:
    file: ./configs/traefik.toml
  nginx-conf:
    file: ./configs/nginx-redirect.conf

secrets:
  traefik-cert:
    file: ./tls/fullchain.pem
  traefik-key:
    file: ./tls/privkey.pem

services:

  traefik:
    image: traefik:1.4
    deploy:
      replicas: 3
      placement:
        constraints:
        - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    ports:
      - target: 80
        protocol: tcp
        published: 80
        mode: ingress
      - target: 443
        protocol: tcp
        published: 443
        mode: ingress
      - target: 8080
        protocol: tcp
        published: 8080
        mode: ingress
    configs:
      - source: traefik-toml-v2
        target: /etc/traefik/traefik.toml
        mode: 444
    secrets:
      - source: tls-cert-internt.mojlighetsministeriet.se
        target: cert.pem
        uid: "0"
        mode: 400
      - source: tls-key-internt.mojlighetsministeriet.se
        target: key.pem
        uid: "0"
        mode: 400

  # letsencrypt:
  #   image: mojlighetsministeriet/letsencrypt
  #   environment:
  #     DOMAINS: internt.mojlighetsministeriet.se
  #   deploy:
  #     replicas: 1
  #     update_config:
  #       parallelism: 1
  #       delay: 10s
  #       failure_action: continue
  #       monitor: 60s
  #       max_failure_ratio: 0.3
  #     restart_policy:
  #       condition: on-failure
  #       delay: 5s
  #       max_attempts: 3
  #       window: 120s
  #     labels:
  #       - traefik.frontend.rule=PathPrefixStrip:/.well-known
  #       - traefik.docker.network=proxy
  #       - traefik.port=80
  #       - traefik.enable=true
  #   networks:
  #     - proxy

  nginx_redirect:
    image: nginx:1.13
    networks:
      - proxy
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - traefik.frontend.entryPoints=http
        - traefik.frontend.rule=PathPrefix:/
        - traefik.docker.network=proxy
        - traefik.port=80
        - traefik.enable=true
    configs:
      - source: nginx-conf
        target: /etc/nginx/conf.d/default.conf
        mode: 444

  swarm-info:
    image: mojlighetsministeriet/swarm-info
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - traefik.frontend.rule=PathPrefixStrip:/swarm-info
        - traefik.docker.network=proxy
        - traefik.port=80
        - traefik.enable=true
    networks:
      - proxy
