version: "3.3"

networks:
  proxy:
    external: true

volumes:
  database:

services:
  mariadb:
    image: jsurf/rpi-mariadb
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    environment:
      # TODO: figure out how this can be moved to secrets instead
      MYSQL_ROOT_PASSWORD: yourrootpassword
      MYSQL_DATABASE: momin
      MYSQL_USER: momin
      MYSQL_PASSWORD: yourrootpassword
    deploy:
      placement:
        platforms:
          architecture: arm64
          os: linux
        constraints: [node.role == manager]
    networks:
      - proxy
